
resources:
- repo: self

jobs:

- job: Job_1
  displayName: Setup
  condition: succeeded()
  pool:
    name: Hosted Ubuntu 1604
  variables:
    resource-group: 'vm-pack-rg'
    region: 'eastus'
    vm-name: 'pack-vm'

  steps:
  - task: AzureCLI@1
    displayName: 'Deploy Builder VM to Azure'
    inputs:
      azureSubscription: '$(subscription-id)'
      scriptPath: 'create-inception.sh'
      arguments: '$(resource-group) $(region) $(vm-name) $(vm-password)'

